apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: ns-22
spec:
  ports:
    - port: 5432
  selector:
    app: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      nodeSelector:
        kubernetes.io/hostname: node-22
      containers:
        - name: db
          image: postgres:16-alpine
          env:
            - name: POSTGRES_USER
              value: app_user
            - name: POSTGRES_PASSWORD
              value: app_password
            - name: POSTGRES_DB
              value: app_db
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: ns-22
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: ns-22
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      nodeSelector:
        kubernetes.io/hostname: node-22
      containers:
        - name: app
          image: kdfrolov/my_app:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: db
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: app_user
            - name: DB_PASSWORD
              value: app_password
            - name: DB_DATABASE
              value: app_db
